namespace _2025_xunit_to_the_limits_src.T8_AsyncCollections_TestContainers;

[CollectionDefinition(nameof(CollectionDefinitionOfTestsWithSameContainer))]
public class CollectionDefinitionOfTestsWithSameContainer : ICollectionFixture<TestFixtureWithContainer4Mongo>
{
}